// Text of the build (the parts 'swiss' and 'riso') and the characters each of its atlases needs. Bars 1–14 design:
// notes/b112/final.md §4.4–4.8, §6.3; build sheet notes/b114/sheet.md §6–7. The hosts are cast in src/content/castBuild.ts
// (generated by scripts/castBuild.mjs); this file places them (S08_CARDS) and holds the strings.
import { CAT, EYES, type Kaomoji, MOUTHS, PROTAGONIST, SHUT, expression, faceText } from '../actors/cast.ts';
import { hash } from '../engine/random.ts';
import { SIGNATURE } from './boot.ts';
import { S06_HOSTS, S08_FACES, S08_FOOTER, S08_HEADLINE } from './castBuild.ts';
import type { TextItem } from './text.ts';

/**
 * The bars 1–14 additions to the approved Swiss and Riso shots that can each be switched off on its own (the story bible's 先保留、再加;
 * build sheet notes/b114/sheet.md §0). Off, the shot draws what v04 drew there, at v04's instants (moved with the map): the identity
 * gates of the sheet's §9 render each one off as well as on. The SCAN bar itself is the map (src/score/film.ts); `pov` only chooses how
 * it looks (the design's fallback rungs; the glass sculpture is the same in every rung).
 */
export type BuildThreads = {
  /** S05 (swiss 1): the lens, the Müller-Brockmann arcs and Saul Bass's cut-paper pieces; off = v04's S05 (the disc lands, the row rule, the slide, the blink on 1.4). */
  readonly lens: boolean;
  /** S06 (swiss 2): the giant face's hop on 2.1& and the red L-ticks re-acquiring his oval on each split. */
  readonly reacquire: boolean;
  /** S07b (swiss 4): 'full' the X-ray POV · 'lite' the colour backplate with only the red scanlines, stamps, reticle, readout and iris ring · false no POV (the hops as a HUD only). */
  readonly pov: 'full' | 'lite' | false;
  /** S08 (swiss 5): the Warhol wave, the guest's red card, the quarantine and the revival; off = v04's ripple and blink wave over the recast poster. */
  readonly infection: boolean;
  /** S08's headline and footer type cards (off: those 26 cards are blank cream cards, infected like the rest). */
  readonly typeCards: boolean;
  /** T2's backs (swiss 5.4): S09's plates converge into register on the fill's sixteenths, ×4 → ×1 (off: v04's backs; the flip itself is the same either way). */
  readonly register: boolean;
  /** A7 and A8: the signature as Swiss small print (525–539) and as the Riso press slug (riso 1). */
  readonly slugs: boolean;
  /** S12 (riso 4): the proof → print steps on the snare 16ths (off: v04's cut to the big face). */
  readonly printSteps: boolean;
  /** S12: the sky roller, the sea's steps and the halftone rings off the sun (off: v04's sky and its rays). */
  readonly sunRings: boolean;
  /**
   * N3: the Swiss corner is clear — no bar counter `NN/61` and no beat squares
   * on an ink tab over swiss 1–5 (off: v04's corner counter, which read `NN/36` in v04).
   */
  readonly cleanCorner: boolean;
  /**
   * N2: S07's giant cropped type behind the glass ω
   * is his own bytes, GLASS_TYPE (off: v04's "150" and "bpm").
   */
  readonly glassBytes: boolean;
};
export const BUILD_THREADS: BuildThreads = {
  // cleanCorner: false — the corner counter stays (the gag: the film counts itself; drop 2 18.2 echoes it).
  lens: true, reacquire: true, pov: 'full', infection: true, typeCards: true, register: true, slugs: true, printSteps: true, sunRings: true, cleanCorner: false, glassBytes: true,
};

/** Swiss poster type (Inter Tight): the title, the footer, v04's "bpm" (S07, `glassBytes` off) and (A7) the signature small print right of the footer, 525–539. */
export const LABELS = { title: 'kaomoji.exe', footer: '150 bpm · 4/4 · swiss grid', bpm: 'bpm', sig: SIGNATURE } as const;
/**
 * S07's type behind the glass ω (BUILD_THREADS.glassBytes; v04: "150" / "bpm"): `big` the giant cropped display type, `small` the small
 * print beside its top. CF 89 is the UTF-8 of his ω — the middle of his signature E2 80 A2 20 CF 89 20 E2 80 A2, which the RAIN bar
 * prints and drop 2 stamps — and U+03C9 its code point: the X-ray of the SCAN bar reads his very bytes and still finds 0 threats.
 */
export const GLASS_TYPE = { big: 'CF 89', small: 'U+03C9 ω' } as const;

/**
 * @deprecated v04's 64 constructed faces (eyes × mouths) of S06 and S08, replaced by real faces of the collection (S06_HOSTS,
 * S08_CARDS): kept until src/shots/swiss.ts reads the cast.
 */
export const SWISS_FACES: readonly Kaomoji[] = EYES.flatMap((_, e) => MOUTHS.map((_, m) => expression(e, m)));
/** The Riso world's faces: the protagonist and the cat. */
export const RISO_FACES: readonly Kaomoji[] = [PROTAGONIST, CAT];
/** The four faces S11's halftone shows in negative, one per beat. */
export const HALFTONE_FACES = ['(=^･ω･^=)', '(•ω•)', '(＾▽＾)', '(≧ω≦)'] as const;
/** S09's flipbook: one face a beat, each drawn four times (a sheet a sixteenth): the protagonist, the cat, a grin, and a shout whose mouth opens wider on every sheet — its last sheet is the first mouth S10 dives into. */
export const FLIPBOOK = [
  ['(•ω•)', '(•ω•)ノ', 'ヽ(•ω•)ノ', '(•ω•)ノ'],
  ['(=^･ω･^=)', '(=^･ω･^=)ﾉ', 'ヽ(=^･ω･^=)ﾉ', '(=^-ω-^=)'],
  ['(≧▽≦)', '(≧▽≦)/', 'ヽ(≧▽≦)ﾉ', '(≧ω≦)'],
  ['(°o°)', '(°O°)', 'ヽ(°O°)ﾉ', 'ヽ(°〇°)ﾉ'],
] as const;
/**
 * The open mouths the camera bursts through, one on each kick from riso 2.1 to riso 3.1 (the first is S09's last sheet): each a kaomoji
 * from the collection, the hole its mouth's counter — round, square, triangle, diamond, round. `setAs`: the face is set character for
 * character where that string sets (each replacing character centred on the one it replaces, at that string's size), so the page, the
 * hole and the flight stay exactly as approved. N1: bar 12's Σ(°ロ°) wore the table-flip core °ロ° (the
 * cast rule, §7) and becomes Σ(・ロ・) — only the eyes change.
 */
export const MOUTH_FACES: readonly { face: string; mouth: string; setAs?: string }[] = [
  { face: 'ヽ(°〇°)ﾉ', mouth: '〇' },
  { face: 'Σ(・ロ・)', mouth: 'ロ', setAs: 'Σ(°ロ°)' },
  { face: '(☆▽☆)', mouth: '▽' },
  { face: '（゜◇゜）', mouth: '◇' },
  { face: '＼(＾O＾)／', mouth: 'O' },
];
/** The mouths whose counters are cut as holes. */
export const MOUTH_CHARS: readonly string[] = [...new Set(MOUTH_FACES.map((m) => m.mouth))];

// ——— The guest and the hero in Swiss ———————————————————————————————————————————————————————————————————————————————————————————

/** The guest (the antivirus): S08's one red card, reversed out in paper; never infected. */
export const GUEST = '(￣▽￣)';
/** His face on his amber card and on every copy. */
export const HERO = '(•ω•)';
/** The blink of the wave (S08 blink wave, every copy): (•ω•) → (-ω-) → (•ω•). */
export const HERO_BLINK = '(-ω-)';

// ——— S08: the poster (swiss 5) ——————————————————————————————————————————————————————————————————————————————————————————————————

/** The poster grid: 16 × 9 cards of 120 px (T2's cards), card (col, row) centred at cardAt (src/shots/swiss.ts): (8, 4) is world (60, 0). */
export const S08_GRID = { cols: 16, rows: 9, cell: 120 } as const;
/**
 * His card (amber #FFB23E, the only amber in Swiss), the guest's (DEFENDER red, the only red card) and the corner: the two cells v04's
 * counter tab covered; with BUILD_THREADS.cleanCorner (N3) two blank cream cards the wave infects like the rest.
 */
export const S08_HERO: readonly [number, number] = [8, 4];
export const S08_GUEST: readonly [number, number] = [12, 2];
export const S08_COUNTER: readonly (readonly [number, number])[] = [[14, 0], [15, 0]];
/** The three copies the antivirus quarantines (threads A6 ×3): boxed by red cut-paper strips on 888, grey 888–892, revived as 2×2s on 900. */
export const S08_QUARANTINE: readonly (readonly [number, number])[] = [[7, 3], [10, 5], [6, 6]];

/** A silkscreen tint (Riso inks only: never red, never amber). */
export type Tint = 'pink' | 'blue' | 'yellow';
/** The Warhol tints, linear-ready hex (Riso pink, blue, yellow) and the quarantine grey. */
export const TINTS: Readonly<Record<Tint | 'grey', string>> = { pink: '#FF48B0', blue: '#0078BF', yellow: '#FFE800', grey: '#9A9A96' };

export type S08Card = {
  col: number;
  row: number;
  /** hero: his amber card · guest: the red card · counter: the corner (v04's counter tab; N3: a blank card) · headline / footer: a type card · face: a host. */
  kind: 'hero' | 'guest' | 'counter' | 'headline' | 'footer' | 'face';
  /** The face or the type card's character ('' for the counter). */
  text: string;
  /** Manhattan distance from his card: the infection wave reaches it on step ⌈d/2⌉ (src/score/build.ts infectFrame). */
  d: number;
  /** The copy's silkscreen tint once infected (every card but his and the guest's; the corner's are cornerTints'). */
  tint?: Tint;
  /** One of the three quarantined copies. */
  quarantine?: true;
};

const at = (c: readonly [number, number], col: number, row: number) => c[0] === col && c[1] === row;
const near = (c: readonly [number, number], col: number, row: number) => Math.max(Math.abs(c[0] - col), Math.abs(c[1] - row)) === 1;
/** A ￣-eyed face (the guest's eyes): never in the 8 cards round the guest. */
const guestEyed = (face: string) => /[￣‾¯]/u.test(face);

/**
 * The tints: hashed per card, so that no two 4-neighbours share a tint and no yellow card touches his amber one (the 8 cards round
 * (8, 4)); his card, the guest's and the counter's take none. Row by row, each card takes the first of its hashed order that its left
 * and upper neighbours and the amber rule allow, backtracking if none does.
 */
function tints(kinds: readonly (readonly string[])[]): (Tint | undefined)[][] {
  const { cols, rows } = S08_GRID;
  const out: (Tint | undefined)[][] = Array.from({ length: rows }, () => Array.from({ length: cols }, () => undefined));
  const cells: [number, number][] = [];
  for (let row = 0; row < rows; row++) for (let col = 0; col < cols; col++) if (!['hero', 'guest', 'counter'].includes(kinds[row][col])) cells.push([col, row]);
  const order = (col: number, row: number): Tint[] => {
    const all: Tint[] = ['pink', 'blue', 'yellow'];
    return all.map((t, i) => [t, hash(col, row, 91 + i)] as const).sort((a, b) => a[1] - b[1]).map(([t]) => t);
  };
  const ok = (col: number, row: number, t: Tint) =>
    !(t === 'yellow' && near(S08_HERO, col, row)) && (col === 0 || out[row][col - 1] !== t) && (row === 0 || out[row - 1][col] !== t);
  const place = (i: number): boolean => {
    if (i === cells.length) return true;
    const [col, row] = cells[i];
    for (const t of order(col, row)) {
      if (!ok(col, row, t)) continue;
      out[row][col] = t;
      if (place(i + 1)) return true;
    }
    out[row][col] = undefined;
    return false;
  };
  if (!place(0)) throw new Error('S08: no tinting satisfies the rules');
  return out;
}

/**
 * N3: the corner's two cards (S08_COUNTER) take tints after every other card is tinted — the first of each one's hashed order that its
 * left and lower neighbours allow — so no tint the poster was approved with changes.
 */
function cornerTints(out: (Tint | undefined)[][]): (Tint | undefined)[][] {
  for (const [col, row] of S08_COUNTER) {
    const all: Tint[] = ['pink', 'blue', 'yellow'];
    const order = all.map((t, i) => [t, hash(col, row, 91 + i)] as const).sort((a, b) => a[1] - b[1]).map(([t]) => t);
    const taken = [[col - 1, row], [col + 1, row], [col, row - 1], [col, row + 1]].map(([c, r]) => out[r]?.[c]);
    const t = order.find((x) => !taken.includes(x) && !(x === 'yellow' && near(S08_HERO, col, row)));
    if (!t) throw new Error(`S08: no tint for the corner card (${col}, ${row})`);
    out[row][col] = t;
  }
  return out;
}

/**
 * Every card of the S08 poster, row by row from the top-left (144): the headline across row 0 (cards 0–10), the footer across row 8
 * (cards 0–14), his card, the guest's, the counter's tab, and S08_FACES in card order on the other 114 — but never a ￣-eyed face in
 * the 8 cards round the guest (such a face swaps with the next eligible one).
 */
export const S08_CARDS: readonly S08Card[] = (() => {
  const { cols, rows } = S08_GRID;
  const kinds: S08Card['kind'][][] = Array.from({ length: rows }, (_, row) =>
    Array.from({ length: cols }, (_, col) => {
      if (at(S08_HERO, col, row)) return 'hero';
      if (at(S08_GUEST, col, row)) return 'guest';
      if (S08_COUNTER.some((c) => at(c, col, row))) return 'counter';
      if (row === 0 && col < [...S08_HEADLINE].length) return 'headline';
      if (row === rows - 1 && col < [...S08_FOOTER].length) return 'footer';
      return 'face';
    }),
  );
  const queue = [...S08_FACES];
  const tint = cornerTints(tints(kinds));
  const out: S08Card[] = [];
  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < cols; col++) {
      const kind = kinds[row][col];
      let text = '';
      if (kind === 'hero') text = HERO;
      else if (kind === 'guest') text = GUEST;
      else if (kind === 'headline') text = [...S08_HEADLINE][col];
      else if (kind === 'footer') text = [...S08_FOOTER][col];
      else if (kind === 'face') {
        const k = near(S08_GUEST, col, row) ? queue.findIndex((f) => !guestEyed(f)) : 0;
        text = queue.splice(Math.max(0, k), 1)[0];
      }
      const d = Math.abs(col - S08_HERO[0]) + Math.abs(row - S08_HERO[1]);
      out.push({ col, row, kind, text, d, ...(tint[row][col] ? { tint: tint[row][col] } : {}), ...(S08_QUARANTINE.some((c) => at(c, col, row)) ? { quarantine: true as const } : {}) });
    }
  }
  if (queue.length) throw new Error(`S08: ${queue.length} faces left over`);
  return out;
})();

/** A quarantined copy revived (900) as a Four-Marilyns 2×2: four (•ω•) at em 20, at (±30, ±30) from the card centre, never red or amber. */
export type Marilyn = { dx: number; dy: number; tint: Tint | 'paper'; ink: 'ink' | 'paper'; off: readonly [number, number] };
const MARILYN: readonly Marilyn[] = [
  { dx: -30, dy: 30, tint: 'paper', ink: 'ink', off: [0, 0] }, // TL: ink on paper
  { dx: 30, dy: 30, tint: 'pink', ink: 'paper', off: [3, -3] }, // TR: paper on a 56 × 56 pink square, off register
  { dx: -30, dy: -30, tint: 'yellow', ink: 'ink', off: [0, 0] }, // BL: ink on yellow
  { dx: 30, dy: -30, tint: 'blue', ink: 'ink', off: [-3, 3] }, // BR: ink on blue, off register
];
/** Each quarantined card's 2×2. On (7, 3), the one in his 8-neighbourhood, the yellow quadrant is the one farthest from his card (TL). */
export const marilyn = (col: number, row: number): readonly Marilyn[] => {
  if (!near(S08_HERO, col, row)) return MARILYN;
  // His card seen from this one (y up: a lower row is further down).
  const hx = (S08_HERO[0] - col) * S08_GRID.cell;
  const hy = (row - S08_HERO[1]) * S08_GRID.cell;
  const away = (q: Marilyn) => Math.hypot(q.dx - hx, q.dy - hy);
  const far = MARILYN.reduce((a, q) => (away(q) > away(a) ? q : a));
  const yellow = MARILYN.find((q) => q.tint === 'yellow')!;
  // The farthest quadrant and the yellow one trade prints.
  return MARILYN.map((q) => (q === far ? { ...q, tint: yellow.tint, ink: yellow.ink, off: yellow.off } : q === yellow ? { ...q, tint: far.tint, ink: far.ink, off: far.off } : q));
};

/** S08's type cards: Inter Tight Black (OFL, the display atlas), ink on cream, one character a card, cap height 84 px, optically centred. */
export const TYPE_CARD = { font: 'Inter Tight', weight: 900, cap: 84 } as const;
/**
 * The Warhol silkscreen, per card (3 frames, from its infection step: the tint wipes in from the edge facing his card on frame 0, the
 * face swaps to him on frame 1, a 6 px hop lands on frame 3): a flat 112 × 112 tint, (•ω•) printed 3 px off register (+3, −3) — ink on
 * pink and yellow, paper on blue — with a 2 px ghost of the tint the other way.
 */
export const SILK = { tint: 112, off: [3, -3], ghost: 2, frames: 3, hop: 6 } as const;
/**
 * The quarantine's Saul Bass red strips, four a card, card-relative px (y up): they fly in from 40 px out (882 → 888, an impact landing
 * on 888), overshooting the corners like hand-laid strips; on the revival (900) each launches 110 px out along its normal, turning
 * ±0.15 rad, α → 0 by 906.
 */
export const BASS_STRIPS: readonly { side: 'top' | 'bottom' | 'left' | 'right'; w: number; h: number; x: number; y: number; rot: number }[] = [
  { side: 'top', w: 150, h: 11, x: 0, y: 66, rot: 0.02 },
  { side: 'bottom', w: 146, h: 13, x: 0, y: -66, rot: -0.015 },
  { side: 'left', w: 12, h: 148, x: -66, y: 0, rot: 0.012 },
  { side: 'right', w: 10, h: 152, x: 66, y: 0, rot: -0.02 },
];
export const STRIP_MOVES = { flyIn: 40, flyOut: 110, turn: 0.15 } as const;
/** The guest on the wave's step 3 (888): a red ring pulse r 70 → 120, 3 px, α 1 → 0 over 8 frames, and a 10 px hop; the rings skip its card. */
export const GUEST_PULSE = { r: [70, 120], width: 3, frames: 8, hop: 10 } as const;
/** S08's camera: zoom 1 → 1.03 about OMEGA_AT over 864–900 (ease out), back to 1 square by 912 (inOutSine); kick punches on top. */
export const S08_ZOOM = 1.03;

// ——— Riso: the slug (riso 1) and S12's print (riso 4) ——————————————————————————————————————————————————————————————————————————

/** A8: the signature as a press slug just right of the bottom-left registration mark — M PLUS Rounded 1c 13 px, the blue plate with a pink ghost (+1.5, +1.5) at 60 %, multiplied; it does not turn. */
export const RISO_SLUG = { x: -770, y: -428, px: 13, ghost: [1.5, 1.5], ghostAlpha: 0.6 } as const;
/** A7: the signature as Swiss small print, right-aligned 24 px left of the footer, Inter Tight 13 px, ink at 60 %, baseline y −478. */
export const SWISS_SMALL_PRINT = { px: 13, alpha: 0.6, baseline: -478, gap: 24 } as const;
/**
 * S12's inversion print on the snare 16ths (src/score/build.ts PRINT_STEPS): S11's rosette screens at these coverages (pink + blue,
 * S11's pitch and angles) on cream, the face at these fractions of BIG's size moving from S11's ω point to BIG's; the blue plate
 * prints solid into the brackets and ω from the second step, the pink into the eyes from the third. Each step a 2-frame launch with a
 * registration clack. The 1248 pin: S11's ω centroid (1247) to the new ω centroid (1248) ≤ 10 px.
 */
export const PRINT = { coverage: [0.75, 0.45, 0.18, 0], scale: [0.76, 0.84, 0.92, 1], solidBlueFrom: 1, solidPinkFrom: 2, pinPx: 10 } as const;
/** S12's sky: halftone screens at pitch 11, Riso angles, printed by a roller front top → bottom (yellow 15 % at the top → 55 % at the horizon; pink 0 → 30 % in the lower third) and un-printed (dots shrinking to 0). */
export const SKY = { pitch: 11, yellow: [0.15, 0.55], pink: [0, 0.3] } as const;
/** S12's sea: the ω rows step 20 px a sixteenth from MERGED (rows alternating direction), once a 32nd from SUNRISE. */
export const SEA_STEP = 20;
/** S12's sun rings (no rays): on every 32nd of SUN_RINGS, 36 yellow-plate dots launch off the sun's rim, 12 → 4 px, r + 10 → r + 160 over 10 frames, α → 0. */
export const SUN_RING = { dots: 36, size: [12, 4], r: [10, 160], frames: 10 } as const;

// ——— S05: the lens (swiss 1) ————————————————————————————————————————————————————————————————————————————————————————————————————

/** The lens: T1's red contracts into this disc (world px on the poster plane, y up), landing on screen at (122, 73), 142 px from the centre. */
export const DISC = { x: 150, y: 30, r: 300 } as const;
/** S05's poster aim from swiss 1.1, a linear glide (zoom geometric) to the unchanged S05_TO {1.104, −48, −40} of src/shots/swiss.ts by swiss 2.1. */
export const S05_FROM = { zoom: 1.22, x: 50, y: -30 } as const;
/**
 * Müller-Brockmann's arcs round the lens (the Beethoven poster's technique; ours: the antivirus's aperture): ring k (0–5) at radius
 * radii[k], stroke widths[k], 4 + k black segments with gaps of 8–20° (hashed per ring), fanning only over −35° … +150° (up and right,
 * the frame crops them; the lower-left quadrant stays his). Drawn rules < arcs < disc < hero. They print outward on 482 + 2k, step
 * ±11° on the kicks of 1.2 and 1.3 (alternate rings turn opposite ways; launch τ 1.5, no bounce), ride with the lens on 1.4 and tighten
 * to 92 % (launch τ 3), breathe 1 % on the hats and blow out (×1.6, α → 0) over 576–582. Stills fallback: the first four rings.
 */
export const ARCS = {
  radii: [390, 470, 550, 640, 740, 860],
  widths: [22, 16, 12, 9, 7, 5],
  segments: (k: number): number => 4 + k,
  gapDeg: [8, 20],
  fanDeg: [-35, 150],
  stepDeg: 11,
  tighten: 0.92,
  breathe: 0.01,
  blowOut: 1.6,
  fallbackRings: 4,
} as const;
/**
 * Saul Bass's cut paper: his five pieces, each an impact landing exactly on its eighth (src/score/build.ts PIECES), from the side it
 * enters by. Each is its glyph cut with a ragged edge (SDF threshold + 0.03 · noise(uv · 40), fixed per piece) and, while it moves,
 * jitters on twos (±2 px, ±1°, re-rolled every second output frame); the landing frame is crisp. Assembled where v04's protagonist sat
 * (src/shots/swiss.ts ROW: em 440, bleeding 8 % off the left, y −250).
 */
export const BASS_PIECES: readonly { ch: string; from: 'left' | 'top' | 'bottom' | 'right' }[] = [
  { ch: '(', from: 'left' },
  { ch: '•', from: 'top' },
  { ch: 'ω', from: 'bottom' },
  { ch: '•', from: 'top' },
  { ch: ')', from: 'right' },
];
export const BASS_CUT = { ragged: 0.03, noiseScale: 40, jitterPx: 2, jitterDeg: 1, onTwos: 2 } as const;

// ——— S06: the re-acquire ticks (swiss 2) ————————————————————————————————————————————————————————————————————————————————————————

/** On each split after the first, 4 red L-ticks snap round his oval (arms 18 px, 3 px wide), launching from 12 px out over 6 frames; the giant face hops 2 % squash and 8 px on 2.1&. */
export const REACQUIRE_TICKS = { arm: 18, width: 3, from: 12, frames: 6, hopSquash: 0.02, hopPx: 8 } as const;

// ——— S07a → S07b: the glass's third hit, the scan, the pull (swiss 3.4 – swiss 5.1) ——————————————————————————————————————————————

/** Where he ends up dead-on, and where every hand-off of the scan bar is pinned: his ω (world px on the poster plane = screen px at 1×). */
export const OMEGA_AT: readonly [number, number] = [60, 0];
/** The third hit (swiss 3.4): a launch (τ 4) of these deltas to the glass's pose, turning him back toward us; the truck decelerates with τ 10 from v04's slope (200 px / 84 frames). */
export const HIT3_POSE = { ry: -0.45, rx: -0.08, rz: 0.03, x: -20, tau: 4, truckTau: 10 } as const;
/** The disc breathes r 300 → 330 over 744–767 (pre-iris), and the iris opens it as a red annulus r 330 → 1250 over 768–774 (launch τ 2: 75 % by 770). */
export const IRIS_RING = { breathe: [300, 330], open: [330, 1250], annulus: 140, tau: 2 } as const;
/** The living drift after the stamp (811–851): rz ±0.01 on a 48-frame sine, x ±3 px; from 816 a push of 2.5 % a beat about OMEGA_AT. */
export const SCAN_DRIFT = { rz: 0.01, period: 48, x: 3, push: 0.025 } as const;

// ——— S07b: the antivirus's POV (swiss 4) ————————————————————————————————————————————————————————————————————————————————————————

/**
 * The antivirus's POV signature (the story bible's 杀毒视角; S07b is its reference, the club, the interlude and drop 2 adapt it): bone on
 * near-black, a Sobel edge, red scanlines crawling, a red reticle with four inward ticks and an open centre, the readout in the slot
 * bottom-left (src/content/boot.ts READOUT_SLOT). Colours are display hex; the red is DEFENDER red (worlds/swiss.ts SWISS.red).
 */
export const DEFENDER_POV = {
  ground: '#0B1216',
  bone: '#CFE0E6',
  ink: 0.85,
  rules: 0.45,
  edge: 0.6,
  red: '#E8402B',
  scanlines: { width: 2, pitch: 9, alpha: 0.16, crawl: 3 },
  reticle: { r: 92, width: 4, ticks: 4, tick: 18, y: 40, hopTau: 1 },
  ping: { r: [92, 160], frames: 8 },
  stamp: { px: 13, weight: 500, cleanAlpha: 0.7, tab: 4, offset: [10, -10] },
} as const;
/** S07's 12 × 12 module grid the reticle scans (160 × 90 px cells, the poster's own module), column k's centre x (k = 0 … 11: −880 … +880). */
export const POV_GRID = { cols: 12, rows: 12, cellW: 160, cellH: 90 } as const;
export const reticleX = (k: number): number => -880 + POV_GRID.cellW * k;

/** The stamp on every cell of S07's 12 × 12 module grid (JetBrains Mono 500, 13 px: `clean` bone 0.7, `✓` red). */
export const CLEAN = 'clean ✓';
/** The POV readout (readout slot, JetBrains Mono 19 px): `· 0 threats` on every frame of the scan; the ✓ only from 810. `[SCAN]` and ✓ red. */
export const povReadout = (cells: number, done = false): string => `[SCAN] grid ${String(cells).padStart(3, '0')}/144 · 0 threats${done ? ' ✓' : ''}`;
/** Every POV string: the readout at each hop (+12 cells a hop, 000 … 144), its ✓ form from 810, the stamp. */
export const POV_TEXTS: readonly string[] = [...Array.from({ length: 13 }, (_, k) => povReadout(12 * k)), povReadout(144, true), CLEAN];

// ——— Atlases ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

const chars = (strings: readonly string[]): string[] => [...new Set(strings.join(''))].filter((c) => c !== ' ' && c !== '　');

/** Every face S06 and S08 draw (jp atlas): the hosts, him, his blink, the guest. */
export const SWISS_CAST: readonly string[] = [...S06_HOSTS.level1, ...S06_HOSTS.level2, ...S06_HOSTS.level3, ...S08_FACES, HERO, HERO_BLINK, GUEST];
export const SWISS_JP: readonly string[] = chars([...SWISS_FACES.map(faceText), SHUT, ...SWISS_CAST]);
// GLASS_TYPE (N2) comes last in its atlases: its new characters pack after every approved cell, so none of those moves.
export const SWISS_DISPLAY: readonly string[] = chars(['0123456789/', S08_HEADLINE, S08_FOOTER, GLASS_TYPE.big]);
export const SWISS_TEXT: readonly string[] = chars([LABELS.title, LABELS.footer, LABELS.bpm, LABELS.sig, GLASS_TYPE.small]);
/** The POV's mono atlas (readout, stamps). */
export const SWISS_MONO: readonly string[] = chars([...POV_TEXTS, '0123456789']);
/** The Riso world's characters as approved (the mouths as v04 set them), with A8's slug (the signature by the bottom-left registration mark, 960–1055). */
const RISO_APPROVED: readonly string[] = chars([...RISO_FACES.map(faceText), SHUT, ...FLIPBOOK.flat(), ...MOUTH_FACES.map((m) => m.setAs ?? m.face), '●', SIGNATURE]);
/** Characters the Riso world gained since (N1: the ・ of Σ(・ロ・)): the scene packs them after the mouths' counters, so no approved cell moves. */
export const RISO_ADDED: readonly string[] = chars(MOUTH_FACES.map((m) => m.face)).filter((c) => !RISO_APPROVED.includes(c));
/** Every character the Riso world draws: the approved ones in their order, then the added ones. */
export const RISO_GLYPHS: readonly string[] = [...RISO_APPROVED, ...RISO_ADDED];

/** Every string the build draws, for check-glyphs. */
export const BUILD_TEXTS: readonly TextItem[] = [
  ...SWISS_FACES.map((k) => ({ role: 'jp' as const, text: faceText(k), where: 'swiss faces (v04)' })),
  ...SWISS_CAST.map((text) => ({ role: 'jp' as const, text, where: 'S06 / S08 cast' })),
  { role: 'jp', text: SHUT, where: 'swiss blink' },
  { role: 'display', text: '0123456789/', where: 'swiss counter and 150 (v04: cleanCorner / glassBytes off)' },
  ...Object.values(GLASS_TYPE).map((text) => ({ role: 'display' as const, text, where: 'S07 glass type (N2)' })),
  { role: 'display', text: S08_HEADLINE, where: 'S08 headline cards' },
  { role: 'display', text: S08_FOOTER, where: 'S08 footer cards' },
  ...Object.values(LABELS).map((text) => ({ role: 'display' as const, text, where: 'swiss labels' })),
  ...POV_TEXTS.map((text) => ({ role: 'mono' as const, text, where: 'S07b POV' })),
  ...RISO_FACES.map((k) => ({ role: 'rounded' as const, text: faceText(k), where: 'riso faces' })),
  ...HALFTONE_FACES.map((text) => ({ role: 'rounded' as const, text, where: 'halftone faces' })),
  ...FLIPBOOK.flat().map((text) => ({ role: 'rounded' as const, text, where: 'S09 flipbook' })),
  ...MOUTH_FACES.map((m) => ({ role: 'rounded' as const, text: m.face, where: 'S10 mouths' })),
  ...[SHUT, '●'].map((text) => ({ role: 'rounded' as const, text, where: 'riso pieces' })),
  { role: 'rounded', text: SIGNATURE, where: 'riso slug (A8)' },
];
