// Generated by scripts/castClub.mjs from the club's build sheet (notes/b58/club-sheet.md §7) — do not edit by hand; change the picks
// there and re-run it. The comic club's cast: 26 friends, each a collection face shown once in the film (infected: its mouth re-inked as
// his amber ω), none anywhere else in the film (NFKC, spaces aside); only the hero, the guest and the cat come back, on purpose.

/** A friend: cast number (the sheet's), the collection face, and the face the club prints (its ω twin, or itself when it already wears ω). */
export type Friend = { readonly n: number; readonly host: string; readonly infected: string };

/** Club 1.2&: the splash crowd, left to right on its arc (infected from the start). */
export const CROWD: readonly Friend[] = [
  { n: 7, host: "☆⌒ヽ(*'､^*)chu", infected: "☆⌒ヽ(*'ω^*)chu" },
  { n: 3, host: "ヽ( ˋ(ｴ)´ )ﾉ", infected: "ヽ( ˋ(ω)´ )ﾉ" },
  { n: 4, host: "／(=⌒ x ⌒=)＼", infected: "／(=⌒ω⌒=)＼" },
  { n: 2, host: "(ﾉ´ヮ`)ﾉ*: ･ﾟ", infected: "(ﾉ´ω`)ﾉ*: ･ﾟ" },
  { n: 5, host: "ヽ(`д´*)ノ", infected: "ヽ(`ω´*)ノ" },
  { n: 6, host: "(ノ)`ω´(ヾ)", infected: "(ノ)`ω´(ヾ)" },
  { n: 9, host: "(｡・//ε//・｡)", infected: "(｡・//ω//・｡)" },
  { n: 1, host: "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧", infected: "(ﾉ◕ω◕)ﾉ*:･ﾟ✧" },
  { n: 8, host: "(〃・ω・)つ由(＾ω＾〃)", infected: "(〃・ω・)つ由(＾ω＾〃)" },
];
/** Club 2.1–2.2&: P1's Lichtenstein girl, infected on 2.2&. */
export const GIRL: Friend = { n: 10, host: "(◕︿◕✿)", infected: "(◕ω◕✿)" };
/** Club 2.3–2.4e: P2's Kirby flexer, infected on 2.4e. */
export const FLEXER: Friend = { n: 11, host: "ᕦ(ò_óˇ)ᕤ", infected: "ᕦ(òωóˇ)ᕤ" };
/** Club bar 3: the Busby Berkeley rings (inner to outer) and how many dancers each holds. */
export const RINGS: readonly { readonly friend: Friend; readonly count: number }[] = [
  { friend: { n: 12, host: "(∩︵∩)", infected: "(∩ω∩)" }, count: 6 },
  { friend: { n: 13, host: "／(=✿ x ✿=)＼", infected: "／(=✿ω✿=)＼" }, count: 10 },
  { friend: { n: 14, host: "v( ‘.’ )v", infected: "v( ‘ω’ )v" }, count: 16 },
];
/** Club 4.3: the dancers inside the lens (the first three are the reticle's hops, tagged `carrier`). */
export const LENS_FACES: readonly Friend[] = [
  { n: 15, host: "Σ>―(〃°ω°〃)♡→", infected: "Σ>―(〃°ω°〃)♡→" },
  { n: 16, host: "(⁄ ⁄•⁄ω⁄•⁄ ⁄)", infected: "(⁄ ⁄•⁄ω⁄•⁄ ⁄)" },
  { n: 17, host: "(*´ー)ﾉ(ノд`)", infected: "(*´ω)ﾉ(ノω`)" },
  { n: 18, host: "(-ω-、)", infected: "(-ω-、)" },
  { n: 19, host: "(｡ŏ﹏ŏ)", infected: "(｡ŏωŏ)" },
  { n: 20, host: "(ｔ▽ｔ)", infected: "(ｔωｔ)" },
];
/** Club 5.4: the reaction balloons (with "!!" and "?!", REACTION_MARKS), in the order they pop. */
export const REACTIONS: readonly Friend[] = [
  { n: 21, host: "(((( ;°Д°))))", infected: "(((( ;°ω°))))" },
  { n: 22, host: "o(〒﹏〒)o", infected: "o(〒ω〒)o" },
  { n: 23, host: "(个_个)", infected: "(个ω个)" },
  { n: 24, host: "(ｏ・_・)ノ”(ノ_<、)", infected: "(ｏ・ω・)ノ”(ノω<、)" },
  { n: 25, host: "(◞‸◟)", infected: "(◞ω◟)" },
  { n: 26, host: "｡ﾟ(｡ﾉωヽ｡)ﾟ｡", infected: "｡ﾟ(｡ﾉωヽ｡)ﾟ｡" },
];
export const REACTION_MARKS: readonly string[] = ["!!", "?!"];
/** Club 5.2, lights out: the friends as their own eye pairs only, at fixed spots, one pair blinking on each sixteenth. */
export const DARK_EYES: readonly string[] = ["◕◕", "òó", "⌒⌒", "∩∩", "✿✿", "‘’", "ŏŏ", "´`"];
/** The faces (•ω•) wears in the club; the flight's a beat each from the throw; the glass's (×ω×) is v04's neon (src/shots/lines.ts HERO.dying). */
export const HERO_INK = {
  inked: "(•ω•)",
  cheer: "ヽ(•ω•)ノ",
  point: "(•ω•)ノ",
  flex: "ᕦ(•ω•)ᕤ",
  kick: "ε=┌(•ω•)┘",
  drop: "ヽ(•ω•)",
  sweat: "(•ω•;)",
  flight: ["Σ(°ω°;)", "(°ω°)", "(ﾟωﾟ;)", "(⊙ω⊙)", "(>ω<)"],
  dying: "(×ω×)",
} as const;
/** The guest (the antivirus): calm with his sunglasses up, wet under the cherry, his eyes red in the dark, red by overprint; the throw's arc. */
export const GUEST_INK = {
  calm: "(￣▽￣)",
  wet: "(・_・)",
  redEyes: "(°_°)",
  rage: "(╯°□°)╯",
  arc: "︵",
} as const;
/** The cat DJ. */
export const CAT_INK = "(=^･ω･^=)";
/** The balloons' marks. */
export const MARKS: readonly string[] = ["…", "♪", "!", "!!", "?!"];
/** Every face the club draws, for the later sections' casts to exclude. */
export const CLUB_CAST: readonly string[] = ["☆⌒ヽ(*'ω^*)chu", "ヽ( ˋ(ω)´ )ﾉ", "／(=⌒ω⌒=)＼", "(ﾉ´ω`)ﾉ*: ･ﾟ", "ヽ(`ω´*)ノ", "(ノ)`ω´(ヾ)", "(｡・//ω//・｡)", "(ﾉ◕ω◕)ﾉ*:･ﾟ✧", "(〃・ω・)つ由(＾ω＾〃)", "(◕︿◕✿)", "(◕ω◕✿)", "ᕦ(ò_óˇ)ᕤ", "ᕦ(òωóˇ)ᕤ", "(∩ω∩)", "／(=✿ω✿=)＼", "v( ‘ω’ )v", "Σ>―(〃°ω°〃)♡→", "(⁄ ⁄•⁄ω⁄•⁄ ⁄)", "(*´ω)ﾉ(ノω`)", "(-ω-、)", "(｡ŏωŏ)", "(ｔωｔ)", "(((( ;°ω°))))", "o(〒ω〒)o", "(个ω个)", "(ｏ・ω・)ノ”(ノω<、)", "(◞ω◟)", "｡ﾟ(｡ﾉωヽ｡)ﾟ｡", "(•ω•)", "ヽ(•ω•)ノ", "(•ω•)ノ", "ᕦ(•ω•)ᕤ", "ε=┌(•ω•)┘", "ヽ(•ω•)", "(•ω•;)", "Σ(°ω°;)", "(°ω°)", "(ﾟωﾟ;)", "(⊙ω⊙)", "(>ω<)", "(×ω×)", "(￣▽￣)", "(・_・)", "(°_°)", "(╯°□°)╯", "︵", "(=^･ω･^=)"];
/** The club's most recognisable friends, best first (all ≤ 6 em wide), for the ending's curtain call (scripts/castCurtain.mjs takes FEATURED[0]). */
export const FEATURED: readonly string[] = ["(◕ω◕✿)", "ᕦ(òωóˇ)ᕤ", "／(=✿ω✿=)＼"];
