// Generated by scripts/castBuild.mjs from the bars 1–14 design (notes/b112/final-cast.json; build sheet notes/b114/sheet.md
// §7) — do not edit by hand; change the picks there and re-run it. Bars 1–14's hosts: real faces of the collection, every one different
// (NFKC, spaces aside), none cast by another section, none wearing his ω, the guest's ￣▽￣ or the table-flip core °□°. The principals
// — him (•ω•), the guest (￣▽￣), the cat (=^･ω･^=) — are not listed; they come back on purpose.

/** intro 2, the RAIN bar: the 8 face columns, one face each, left to right; drawn rotated 90° CW in the log's pink (mono atlas). */
export const RAIN_FACES: readonly string[] = ["(ᵔ◡ᵔ)", "(°◡°♡)", "(・‿・)", "(*^^)/", "(^人^)", "(◕ᴗ◕✿)", "(づ◡﹏◡)づ", "(´ ∀ ` *)"];
/** swiss 2 (S06), the split 1 → 4 → 16 → 64: the hosts each level adds, in anchor order (jp atlas). */
export const S06_HOSTS = {
  level1: ["Σ(□_□)", "(O_O;)", "(⊙_◎)"],
  level2: ["┐( ´ д ` )┌", "(￢ ￢)", "m(_ _)m", "(◎ ◎)ゞ", "ヽ(ー_ー )ノ", "(→_→)", "(^_<)〜☆", "Σ(￣。￣ﾉ)", "(⌒_⌒;)", "(☞ﾟヮﾟ)☞", "(￣^￣)ゞ", "ヽ(ˇヘˇ)ノ"],
  level3: ["(~˘▽˘)~", "≧( ° ° )≦", "ヽ(♡‿♡)ノ", "(o-_-o)", "U^ｪ^U", "( ˘⊖˘)", "(·(エ)·)", "(//▽//)", "(o´〰`o)", "／(＞×＜)＼", "／(^ x ^)＼", "(= ; ｪ ; =)", "<(￣ ﹌ ￣)>", "(≡^∇^≡)", "ζ°)))彡", "(」＞＜)」", "(.❛ ᴗ ❛.)", "(^.~)", "╮(︶︿︶)╭", "(・Θ・)", "ヾ( ￣O￣)ツ", "♡( ◡‿◡ )", "(≧◦◦≦)", "┐(￣ヘ￣;)┌", "(ㆆ_ㆆ)", "（・□・；）", "ヽ(´o｀;)ノ", "(♡˙︶˙♡)", "(─‿‿─)♡", "(♡μ_μ)", "(▰˘◡˘▰)", "(╯✧▽✧)╯", "√(￣‥￣√)", "└(￣-￣└))", "(／(ｴ)＼)", "ＵＴｪＴＵ", "(・8・)", "(:3っ)っ", "(ﾉД`)", "ヽ(。_°)ノ", "Σ(ﾟДﾟ)", "(＃`Д´)", "(┳Д┳)", "(ﾒ`ﾛ´)", "(¬▂¬)", "(＿ ＿*) Z z z", "(¦3[▓▓])", "(ー。ー)"],
} as const;
/** swiss 5 (S08), the poster: the 114 faces in card order (src/content/build.ts S08_CARDS places them; jp atlas). */
export const S08_FACES: readonly string[] = ["☆ ～('▽^人)", "( ´_ゝ`)", "(◞‸◟；)", "(≧◠◡◠≦)✧", "(˶ᵔ ᵕ ᵔ˶)♡", "♪(/_ _ )/♪", "__φ(◎◎ヘ)", "(／ˍ・、)", "(°)#))<<", "(￣(00)￣)", "(^₃^)₌₃♕", "☆⌒(>。<)", "ヽ(　￣д￣)ノ", "*(ﾉ▽ﾉ)", "(◣∀◢)ψ", "(￣3￣)♡", "(シ_ _)シ", "⚞^. .^⚟", "(＾＾＃)", "∑d(°∀°d)", "V●ᴥ●V", "乁(ツ)ㄏ", "U・ᴥ・U", "(◉Θ◉)", "\\(￣ﾊ￣)", "（ミ￣ー￣ミ）", "(・ε・)", "(<_<)", "(っ´▽`)っ", "(￣ ¨ヽ￣)", "₍ᐢ..ᐢ₎♡", "(;;;*_*)", "( ﾟｏ⌒)", "/ᐢ⑅ᐢ\\", "●︿●", "(￢з￢)", "(＋_＋)", "╮( ˘ ､ ˘ )╭", "(☆_☆)", "(・ヘ・?)", "(￣(工)￣)", "(ᴗ˳ᴗ)", "┐(´～｀)┌", "(*/。＼)", "(¬‿¬)b", "(˘ ³˘)♥", "( ˶ˆᗜˆ˵ )", "┗(・o･)┓♪", "／(=ㅅ=)＼", "(＠´ー`)ﾉﾞ", "ヽ(>∀<☆)ノ", "◄.►", "₍ᐢ・⚇・ᐢ₎", "☆(>ᴗ•)", "><(((°>", "(ᵔ(oo)ᵔ)", "／(=ｖ=)＼", "__φ(。。)", "(・人・)", "(´−`) ﾝｰ", "(ﾟﾛﾟ)", "( ᵘ ᵕ ᵘ ⁎)", "(╯︵╰,)", "( ・◇・)", "(-_-;)", "(´ ε ` )♡", "(^◕ᴥ◕^)", "◎[▪‿▪]◎", "(￣Θ￣)", "(◔_◔)", "(*￣ii￣)", "(*ﾟｰﾟ)ゞ", "(￣﹃￣)", "(/▿＼ )", "(ノ_<。)", "o(TヘTo)", "ヽ(`⌒´メ)ノ", "ψ( `∇´ )ψ", "ヾ(`ヘ´)ﾉﾞ", "ヽ(‵﹏´)ノ", "Σ(▼□▼メ)", "(҂`з´)", "〣( ºΔº )〣", "(ᓀ ᓀ)", "(´；д；`)", "ヾ(*'▽')", "( ~*-*)~", "( -_・)", "☆⌒(ゝ。∂)", "(=⌒‿‿⌒=)", "ʕ ᵔᴥᵔ ʔ", "ヾ(￣◇￣)ノ〃", "(〜￣△￣)〜", "(ᵕ—ᴗ—)", "(=ＴェＴ=)", "(π_π)", "(ToT)", "(TдT)", "(っ- ‸ – ς)", "(ʘ言ʘ╬)", "(●__●)", "☆ヽ(o_ _)o", "(=｀ェ´=)", "／(•ㅅ•)＼", "／(=∵=)＼", "／(◕ x ◕)＼", "ʕ→ᴥ←ʔ", "(⊃･ᴥ･)つ", "(θ‿θ)", "(-ι_- )", "(｀∀´)Ψ", "(－‿◦)", "(ﾒ▼_▼)", "(๑´ㅂ`๑)"];
/** S08's type cards (Inter Tight Black, display atlas), one character per card: the headline (row 0, cards 0–10) and the footer (row 8, cards 0–14). */
export const S08_HEADLINE = "KAOMOJI.EXE";
export const S08_FOOTER = "150BPM·4/4·16×9";
/** Swap-ins, in order of preference (re-run scripts/castBuild.mjs after a swap). */
export const BUILD_RESERVE: readonly string[] = ["┐( ˘_˘ )┌", "(*¯︶¯*)", "(¬_¬ )", "ʚ₍ᐢ. .ᐢ₎ɞ", "(^._.^)ﾉ"];
/** Every host face of bars 1–14, for the later sections' casts to exclude. */
export const BUILD_CAST: readonly string[] = [...RAIN_FACES, ...S06_HOSTS.level1, ...S06_HOSTS.level2, ...S06_HOSTS.level3, ...S08_FACES];
