// Generated by scripts/castBreak.mjs from the break's build sheet (notes/bid2/break-sheet2.md §8) — do not edit by hand; change
// the picks there and re-run it. The interlude's cast: many different faces, none twice in the break and none anywhere else in the film
// (NFKC, spaces aside), but the hero, the guest and the cat, who come back on purpose, and the system's own faces. Two layers, as in
// src/score/break.ts: the v04 exports (as built, drawn by the carried-over code) and the v2 ones (the design's).

// ——— v04 (as built) ——————————————————————————————————————————————————————————————————————————————————————————————————————————————

/** The faces (•ω•) wears in the break (his type: M PLUS Rounded). `tofu`: his right eye is a drawn tofu box tagged 20 22, never a missing glyph. `ready` and `zoom` are drawn without their accents: his BROWS drop in. */
export const HERO_FACES = {
  dying: "(×ω×)",
  pain: "(>ω<)",
  dizzy: "(＠ω＠)",
  reroll: ["(◎ω◎)", "(⊙ω⊙)", "(●ω●)", "(×ω×)"],
  tofu: "(•ω•)",
  dazed: "(－ω－)",
  awake: "(•ω•)",
  starstruck: "(☆ω☆)",
  wave: "(⌒ω⌒)ﾉ",
  squee: "(*≧ω≦*)",
  ready: "(ง•ω•)ง✧",
  zoom: "─=≡Σ((( つ•ω•)つ",
} as const;
/** His brows, from ⸜(*ˊᗜˋ*)⸝, dropped over his eyes (v04: break 6.1e, left ˋ, and 6.1&, right ˊ; v2: 7.1e / 7.1& and 8.4& / 8.4& + 3). */
export const BROWS: readonly [string, string] = ["ˋ", "ˊ"];
/** The peekers of v04's break bars 2–4, in order of appearance (the guest peeks third: GUEST_PEEK). */
export const PEEKERS: readonly string[] = ["▼・ᴥ・▼", "( ° ∀ ° )ﾉﾞ", "(・_・;)", "┬┴┬┴┤(･_├┬┴┬┴", "(´･_･`)"];
/** The gasp of break 4.4: four at once. */
export const SHOCKED: readonly string[] = ["(」゜ロ゜)」", "＼(º □ º l|l)/", "／(=☉ x ☉=)＼", "ʕ ˵• ₒ •˵ ʔ"];
/** Break bar 5's dancers per block, in order of appearance (break-sheet §4.9). */
export const DANCERS = {
  coral: ["♪(┌・。・)┌", "┌(★o☆)┘", "⁽⁽◝( • ω • )◜⁾⁾", "✺◟( • ω • )◞✺", "┐(︶▽︶)┌", "╮(︶▽︶)╭"],
  mint: ["└(＾＾)┐", "┌(＾＾)┘", "₍₍ (ง ˘ω˘ )ว ⁾⁾", "ʚ(｡˃ ᵕ ˂ )ɞ"],
  yellow: ["♪♪♪ ヽ(ˇ∀ˇ )ゞ", "⸜( *ˊᵕˋ* )⸝"],
} as const;
/** The cocktail guest: guilty, peeking in red (v04 3.3&; v2 3.2&); v04: forgiven, waving back on break 5.4 (v2: spying, then infected). */
export const GUEST_PEEK = "|_￣))";
export const GUEST_WAVE = "(￣▽￣)ノ";
/** The Riso cat, dancing on the violet block. */
export const CAT = "(=^･ω･^=)";
/** The system's faces in the window (E5), kept on purpose. */
export const DIALOG_FACE = "(；・∀・)";
export const GRANTED_FACE = "ヽ(°〇°)ﾉ";
/** Every face v04's break drew. */
export const BREAK_CAST_V04: readonly string[] = ["(×ω×)", "(>ω<)", "(＠ω＠)", "(◎ω◎)", "(⊙ω⊙)", "(●ω●)", "(•ω•)", "(－ω－)", "(☆ω☆)", "(⌒ω⌒)ﾉ", "(*≧ω≦*)", "(ง•ω•)ง✧", "─=≡Σ((( つ•ω•)つ", "▼・ᴥ・▼", "( ° ∀ ° )ﾉﾞ", "(・_・;)", "┬┴┬┴┤(･_├┬┴┬┴", "(´･_･`)", "(」゜ロ゜)」", "＼(º □ º l|l)/", "／(=☉ x ☉=)＼", "ʕ ˵• ₒ •˵ ʔ", "♪(┌・。・)┌", "┌(★o☆)┘", "⁽⁽◝( • ω • )◜⁾⁾", "✺◟( • ω • )◞✺", "┐(︶▽︶)┌", "╮(︶▽︶)╭", "└(＾＾)┐", "┌(＾＾)┘", "₍₍ (ง ˘ω˘ )ว ⁾⁾", "ʚ(｡˃ ᵕ ˂ )ɞ", "♪♪♪ ヽ(ˇ∀ˇ )ゞ", "⸜( *ˊᵕˋ* )⸝", "|_￣))", "(￣▽￣)ノ", "(=^･ω･^=)", "(；・∀・)", "ヽ(°〇°)ﾉ"];

// ——— v2 (the design) ——————————————————————————————————————————————————————————————————————————————————————————————————————————————

/** His new faces (design §9.2): the coaster (seated, armsUp, lift, airtime, rattle, rewound), the fake drop (frontal, flying, squashed, look, getsIt). `frontal` and `getsIt` are drawn without accents: his BROWS drop in. `look` is ( ・ω・)?, its ? popping a 32nd after the eyes. */
export const HERO_FACES_V2 = {
  seated: "(⊙ω⊙)",
  armsUp: "\\(✦ω✦)/",
  lift: "(｀•ω•´)",
  airtime: "(✪ω✪)",
  rattle: ["(✦ω✦)", "(⊙ω⊙)"],
  rewound: "Σ(⊙ω⊙)",
  frontal: "(ง•ω•)ง",
  flying: "(っ≧ω≦)っ",
  squashed: "(≧ω≦)",
  look: "( ・ω・)?",
  getsIt: "(•ω•)",
} as const;
/** His hands splayed flat on the film (break 8.3e → the end): two of these, drawn on their own. */
export const PAWS = "っ";
/** The peekers of v2, in order (the guest peeks third, on 3.2&: GUEST_PEEK). */
export const PEEKERS_V2: readonly string[] = ["▼・ᴥ・▼", "( ° ∀ ° )ﾉﾞ", "(・_・;)"];
/** v04's peekers cut from the interlude for clutter (design §9.3): released for other sections. */
export const RELEASED: readonly string[] = ["┬┴┬┴┤(･_├┬┴┬┴", "(´･_･`)"];
/** The guest spying beside the cat (break 5.3), then infected — his ▽ an amber ω — waving once (5.4e). */
export const GUEST_SPY = "(￣▽￣)";
export const GUEST_INFECTED = "(￣ω￣)ノ";
/** Every face the interlude draws (v2), for the other sections' casts to exclude and the curtain call to credit. */
export const BREAK_CAST: readonly string[] = ["(×ω×)", "(>ω<)", "(＠ω＠)", "(◎ω◎)", "(⊙ω⊙)", "(●ω●)", "(•ω•)", "(－ω－)", "(☆ω☆)", "(⌒ω⌒)ﾉ", "(*≧ω≦*)", "(ง•ω•)ง✧", "─=≡Σ((( つ•ω•)つ", "\\(✦ω✦)/", "(｀•ω•´)", "(✪ω✪)", "(✦ω✦)", "Σ(⊙ω⊙)", "(ง•ω•)ง", "(っ≧ω≦)っ", "(≧ω≦)", "( ・ω・)?", "▼・ᴥ・▼", "( ° ∀ ° )ﾉﾞ", "(・_・;)", "(」゜ロ゜)」", "＼(º □ º l|l)/", "／(=☉ x ☉=)＼", "ʕ ˵• ₒ •˵ ʔ", "♪(┌・。・)┌", "┌(★o☆)┘", "⁽⁽◝( • ω • )◜⁾⁾", "✺◟( • ω • )◞✺", "┐(︶▽︶)┌", "╮(︶▽︶)╭", "└(＾＾)┐", "┌(＾＾)┘", "₍₍ (ง ˘ω˘ )ว ⁾⁾", "ʚ(｡˃ ᵕ ˂ )ɞ", "♪♪♪ ヽ(ˇ∀ˇ )ゞ", "⸜( *ˊᵕˋ* )⸝", "|_￣))", "(￣▽￣)", "(￣ω￣)ノ", "(=^･ω･^=)", "(；・∀・)", "ヽ(°〇°)ﾉ"];
