// Generated by scripts/castDrop2.mjs from the build sheet's picks (notes/d2build/sheet.md §7.2) — do not edit by hand; change the
// picks there and re-run it. Drop 2's and the ending's cast: many different faces, none twice and none already cast in Drop 1 or the
// break (NFKC and near twins), but the hero, the guest and the cat, who come back on purpose. Each face is drawn whole, as one atlas
// key, in the font role listed (check-glyphs checks it through src/content/drop2.ts and outro.ts).
import type { FontRole } from '../engine/fonts.ts';

export type CastFace = { face: string; role: FontRole; where: string };

/** S27: the quiet motifs through drop2 1.2 (the log column’s two friends, the Swiss cell’s); from drop2 1.3 his face is the subject. */
export const S27_CAST: readonly CastFace[] = [
  { face: "°˖✧◝(⁰▿⁰)◜✧˖°", role: 'mono', where: "S27 terminal region: the log column (pink)" },
  { face: "....φ(・∀・*)", role: 'mono', where: "S27 terminal region: the log column (pink), taking notes" },
  { face: "( ´ ∀ `)ノ～ ♡", role: 'jp', where: "S27 Swiss region: the face in a grid cell, waving on the open hats through 27.2" },
];

/** S28: the cube faces’ motifs — Swiss friend groups, Riso nested faces, LED marquee rows, neon tube dancers. */
export const S28_CAST: readonly CastFace[] = [
  { face: "ヽ(∀° )人( °∀)ノ", role: 'jp', where: "S28 Swiss face: friend groups" },
  { face: "＼(＾∀＾)メ(＾∀＾)ノ", role: 'jp', where: "S28 Swiss face: friend groups" },
  { face: "(*＾ω＾)人(＾ω＾*)", role: 'jp', where: "S28 Swiss face: friend groups" },
  { face: "o(^^o)(o^^o)(o^^o)(o^^)o", role: 'jp', where: "S28 Swiss face: friend groups" },
  { face: "(((￣(￣(￣▽￣)￣)￣)))", role: 'jp', where: "S28 Riso face: the pink nested faces" },
  { face: "(°(°ω(°ω°(☆ω☆)°ω°)ω°)°)", role: 'jp', where: "S28 Riso face: the blue nested faces" },
  { face: "☆*:.｡.o(≧▽≦)o.｡.:*☆", role: 'dot', where: "S28 LED face: the second marquee row" },
  { face: "ヽ( ⌒o⌒)人(⌒-⌒ )ﾉ", role: 'dot', where: "S28 LED face: the third marquee row" },
  { face: "♪♬((d⌒ω⌒b))♬♪", role: 'rounded', where: "S28 neon face: tube dancers" },
  { face: "♬♫♪◖(● o ●)◗♪♫♬", role: 'rounded', where: "S28 neon face: tube dancers" },
  { face: "ヽ(≧◡≦)八(o^ ^o)ノ", role: 'rounded', where: "S28 neon face: tube dancers" },
];

/** S30: the VOX lane’s notes, in hit order (the hook’s notes of drop2 bar 5). */
export const S30_VOX: readonly CastFace[] = [
  { face: "(ﾉ´ヮ´)ﾉ*:･ﾟ✧", role: 'jp', where: "S30 VOX note 2880" },
  { face: "˚✧₊⁎(˃ᴗ˂)⁎⁺˳✧", role: 'jp', where: "S30 VOX note 2892" },
  { face: "(*˘︶˘*).｡.:*♡", role: 'jp', where: "S30 VOX note 2898" },
  { face: "(∩˃o˂∩)♡", role: 'jp', where: "S30 VOX note 2916" },
  { face: "｡ﾟ( ﾟ^∀^ﾟ)ﾟ｡", role: 'jp', where: "S30 VOX note 2928" },
  { face: "(⊃｡•́‿•̀｡)⊃", role: 'jp', where: "S30 VOX note 2952" },
  { face: "\\( ˙▿˙ )/( ˙▿˙ )/", role: 'jp', where: "S30 VOX note 2964" },
];

/** S30: the KICK lane’s notes, in hit order. */
export const S30_KICK: readonly CastFace[] = [
  { face: "(๑•̀ㅁ•́๑)✧", role: 'jp', where: "S30 KICK note 2880" },
  { face: "ᕦ( ͡° ͜ʖ ͡°)ᕤ", role: 'jp', where: "S30 KICK note 2904" },
  { face: "ヽ(≧Д≦)ノ", role: 'jp', where: "S30 KICK note 2928" },
  { face: "(☞ ͡° ͜ʖ ͡°)☞", role: 'jp', where: "S30 KICK note 2952" },
];

/** S30: the CLAP lane’s notes, in hit order. */
export const S30_CLAP: readonly CastFace[] = [
  { face: "(*・∀・)爻(・∀・*)", role: 'jp', where: "S30 CLAP note 2904" },
  { face: "Ψ( `∀)(∀´ )Ψ", role: 'jp', where: "S30 CLAP note 2952" },
];

/** S31: the dizzy faces packed into the overflowing gauge (cycling, 22 px). */
export const S31_GAUGE: readonly CastFace[] = [
  { face: "(x_x)", role: 'jp', where: "S31 gauge fill: dizzy faces" },
  { face: "(☆_@)", role: 'jp', where: "S31 gauge fill: dizzy faces" },
  { face: "☆(＃××)", role: 'jp', where: "S31 gauge fill: dizzy faces" },
  { face: "(×_×)⌒☆", role: 'jp', where: "S31 gauge fill: dizzy faces" },
  { face: "(ﾒ﹏ﾒ)", role: 'jp', where: "S31 gauge fill: dizzy faces" },
  { face: "(×﹏×)", role: 'jp', where: "S31 gauge fill: dizzy faces" },
  { face: "@_@", role: 'jp', where: "S31 gauge fill: dizzy faces" },
  { face: "[ ± _ ± ]", role: 'jp', where: "S31 gauge fill: dizzy faces" },
];

/** The reel (drop2 18, as built): the cards’ motifs (neon, LED, Swiss); the Riso card’s cat is CAT. */
export const REEL_CAST: readonly CastFace[] = [
  { face: "ヽ(￣д￣;)ノ=3=3=3", role: 'rounded', where: "bar 33 neon card: the cyan tube runner" },
  { face: "─=≡Σ((( つ＞＜)つ", role: 'dot', where: "bar 33 LED card: the marquee" },
  { face: "ε=ε=┌( >_<)┘", role: 'dot', where: "bar 33 LED card: the marquee" },
  { face: "( ´ ω ` )ノﾞ", role: 'jp', where: "bar 33 Swiss card: waving in a cell" },
];

/** The guest (drop 1’s cocktail guest), back with a fresh cocktail for the last drop (E10). */
export const GUEST: CastFace = { face: "(￣▽￣)", role: 'rounded', where: "E10: the guest with a fresh cocktail (amber neon tube), bars 34.1–34.2" };

/** The guest flips the table and leaves: a line of the crash log. */
export const GUEST_FLIP: CastFace = { face: "(╯°□°)╯︵ ┻━┻", role: 'mono', where: "the crash log: the guest flips the table and leaves" };

/** The guest waving in S28’s LED marquee, as built (the marquee now shows GUEST_WAVE_INFECTED). */
export const GUEST_WAVE: CastFace = { face: "(￣▽￣)/♫•*¨*•.¸¸♪", role: 'dot', where: "S28 LED face: the first marquee row, the guest waving" };

/** The Riso cat, home on the reel’s Riso card (drop2 18). */
export const CAT: CastFace = { face: "(=^･ω･^=)", role: 'jp', where: "bar 33 Riso card: the cat in the blue plate" };

/** The guest infected (since the interlude): E10’s face, red with an amber ω, wearing the reticle hat; Defender’s avatar after the touché. */
export const GUEST_INFECTED: CastFace = { face: "(￣ω￣)", role: 'rounded', where: "E10 (drop2 19.1–19.3): the guest, infected since the interlude — a red neon tube with an amber ω, the reticle as a party hat; Defender’s avatar after the touché (drop2 15.2)" };

/** Defender v1, infected and sweating: W1’s red row and the kernel’s slot. */
export const GUEST_V1: CastFace = { face: "(￣ω￣;)", role: 'mono', where: "Defender v1 (infected, sweating): W1’s red row (drop2 1.2) and the kernel’s slot (drop2 8)" };

/** The guest waving in S28’s LED marquee, infected (a composed variant of GUEST_WAVE). */
export const GUEST_WAVE_INFECTED: CastFace = { face: "(￣ω￣)/♫•*¨*•.¸¸♪", role: 'dot', where: "S28 LED face: the first marquee row, the guest waving — infected since the interlude (logged change)" };

/** Defender is the guest: its avatar’s states, the rowers, the cannon, the athlete. Not in CAST_DROP2 (the curtain wall leaves the guest out; its principal() test does not catch ￣Д￣ or ￣□￣). */
export const GUEST_VARIANTS: readonly CastFace[] = [
  { face: "(；￣Д￣)", role: 'jp', where: "Defender v2.0’s avatar after the first breach (drop2 11.3); the arcade’s cannon (drop2 12, in pixels)" },
  { face: "(￣□￣」)", role: 'jp', where: "the wave’s rowers looking up (drop2 10.3); Defender v2.0’s avatar after the line clear (drop2 13.4)" },
  { face: "╮(￣ω￣;)╭", role: 'jp', where: "Defender giving up (drop2 17.4): the big type and the avatar" },
];

/** Fresh, checked, unused faces, for a builder who needs one more. */
export const SPARES: readonly string[] = ["ʕ•̀ω•́ʔ✧","( ˘ ɜ˘) ♬♪♫","♪♪(o*゜∇゜)o～♪♪","(((o(*°▽°*)o)))","(ﾉ≧∇≦)ﾉ ﾐ ┸┸","ʕ •̀ o •́ ʔ","＼( ˋ Θ ´ )／","(｡•́︿•̀｡)","(┬┬﹏┬┬)","ψ(▼へ▼メ)～→","(＃＞＜)","▓▒░(°◡°)░▒▓","(⊙︿⊙)","{{ (>_<) }}","(ʘ ͟ʖ ʘ)","(｡╯︵╰｡)","(◞︿◟)","ε===(っ≧ω≦)っ"];

/** Every face drop 2 draws, each once: the guest (his infected faces too) and the cat included, the guest's other variants, the hero and the ending's log not. */
export const CAST_DROP2: readonly string[] = [...S27_CAST, ...S28_CAST, ...S30_VOX, ...S30_KICK, ...S30_CLAP, ...S31_GAUGE, ...REEL_CAST, GUEST_WAVE_INFECTED, CAT, GUEST, GUEST_INFECTED, GUEST_V1].map((c) => c.face);
