// What the transition and the cosmos draw (the parts 'transition', 2 bars, and 'cosmos', 6 bars: "VERTIGO ∞ · LIGHTSPEED PRESS"): every
// on-screen string, for scripts/check-glyphs.mjs and for their shots to import (strings live here; the shots import them, never the other
// way round). Build sheet notes/bcos/sheet.md §7–§8; design notes/cosmos3/final.md §7, §8, §10. The faces are the cast's
// (src/content/castCosmos.ts, generated by scripts/castCosmos.mjs). Roles are the type each is drawn in (check-glyphs tests every character
// against its role's stack only): the print films' and gates' knocked-out faces in Noto Sans JP Black (`jp`); every face of the cosmos, the
// bang's face-parts and the Moon's zzZ in M PLUS Rounded 1c ExtraBold (`rounded`); the Powers-of-Ten labels, the planets' names, the big
// threat counts and the ring-counter in Inter Tight Black (`display`); the slug, the edition numbers, the captions and legends, the
// filaments, the Defender's red lines and the party monitor in JetBrains Mono (`mono`).
//
// Raised digits: the design sets exponents as raised digits at 0.55 em, never as superscript code points, with U+2212 for the minus. A
// string here marks a raised run between carets — `10^−7^ m` — and raisedRuns() splits it for the typesetter; plain() is what is drawn.
// The film and the readout never decode the signature (no • or ω beside the bytes).
import { CROWDS, DEFENDER_FACE, EARTH_HOSTS, FILM_POSES, FLINCH_FACES, GALAXY_STARS, GATE_FACES, HERO_FACES, MOON_FACES, PLANETS, REAM_FACES, SUN_FACE, WEB_NODES, WINKS, BANG_PARTS } from './castCosmos.ts';
import type { TextItem } from './text.ts';

// ——— Raised runs ——————————————————————————————————————————————————————————————————————————————————————————————————————————————

/** A run of type: `raised` runs are set at 0.55 em, lifted to the cap line (the design's exponents). */
export type Run = { readonly text: string; readonly raised: boolean };
/** `s` split at its carets into plain and raised runs (`10^−7^ m` → 10 · −7 raised · ' m'); empty runs dropped. */
export const raisedRuns = (s: string): Run[] =>
  s
    .split('^')
    .map((text, i) => ({ text, raised: i % 2 === 1 }))
    .filter((r) => r.text !== '');
/** What `s` draws: its text without the carets. */
export const plain = (s: string): string => s.replaceAll('^', '');

/** U+2212, the label's minus (never the hyphen). */
export const MINUS = '−';

// ——— The signature (threads.md (b) rows 4 and 5) ————————————————————————————————————————————————————————————————————————————————

/** His bytes: `• ω •` in UTF-8, upper-case hex one space apart (E2 80 A2 20 CF 89 20 E2 80 A2). Printed, never decoded. */
export const SIGNATURE = [...new TextEncoder().encode('• ω •')].map((b) => b.toString(16).toUpperCase().padStart(2, '0')).join(' ');
/** The bytes one by one (the web's filaments are typeset from them, one byte a cell, looping along each edge). */
export const SIGNATURE_BYTES: readonly string[] = SIGNATURE.split(' ');

// ——— Bars 13–14: the print films ——————————————————————————————————————————————————————————————————————————————————————————————

/** A film's edition number (JetBrains Mono 11 px, bottom-right of its window): `copy 001/∞`, `copy 002/∞` … one per film, as pasted. */
export const edition = (k: number): string => `copy ${String(k).padStart(3, '0')}/∞`;
/** The most films any frame numbers: the 18 pasted in bar 1 and the ones born in flight (one every 20 units, to the crash: ≤ 140). */
export const MAX_EDITION = 160;
/** The signature slug up film 1's left window edge (blue, JetBrains Mono 13 px), printed from transition 1.1 while the plates fly. */
export const SLUG = `${SIGNATURE} · kaomoji.exe · ${edition(1)}`;
/** The Y films' strips: knocked-out glints (the Y plate carries only light and his sun; hosts live on P and B). */
export const GLINTS = ['✦', '✧'] as const;

// ——— Bars 15–20: the Powers-of-Ten labels, captions and legends (design §4; Eames) —————————————————————————————————————————————

export type LevelId = 'bang' | 'earth' | 'solar' | 'galaxy' | 'web' | 'horizon';
/**
 * Each level's label (Inter Tight Black: the scale, raised exponent), its caption and its legend (JetBrains Mono): the bang's caption flies
 * in under his card on 1.3 (343 amber, THREATS red); every other level's lands with the label on its downbeat. The horizon has no caption:
 * its name is the Defender's word, `sandbox`, said in red on 6.3.
 */
export const LEVEL_TYPE: Readonly<Record<LevelId, { label: string; caption: string | null; legend: string }>> = {
  bang: { label: `10^${MINUS}7^ m`, caption: 'VIRUS · 343 THREATS', legend: '1 ● = 1 copy' },
  earth: { label: '10^7^ m', caption: 'EARTH · 8.1×10^9^ HOSTS', legend: '1 ● = 1 person' },
  solar: { label: '10^13^ m', caption: 'SOLAR SYSTEM', legend: '1 ● = 1 planet' },
  galaxy: { label: '10^21^ m', caption: 'MILKY WAY', legend: '1 ● = 1 star' },
  web: { label: '10^24^ m', caption: 'COSMIC WEB', legend: '1 ● = 1 galaxy' },
  horizon: { label: '10^26^ m', caption: null, legend: '1 band = 1 universe' },
};
/** The exponent's odometer reads `10^e^ m` for any e it rolls through (score EXPONENT), and lies down as ∞ on cosmos 6.2. */
export const scaleLabel = (e: number): string => `10^${e < 0 ? MINUS : ''}${Math.abs(e)}^ m`;
export const INFINITY_SIGN = '∞';
/** The planets' names on their rings of kinetic type (Inter Tight Black, cap ≈ 0.12 of the ring). */
export const PLANET_NAMES: readonly string[] = PLANETS.map((p) => p.name);
/** The Moon's card keeps its zzZ as type beside the face, before and after the beam (the cast's MOON_FACES). */
export const MOON_ZZZ = 'zzZ';

// ——— The threat count (threads.md (c): a display count is an amber number and a red word) ——————————————————————————————————————

export const THREAT_WORD = { one: 'THREAT', many: 'THREATS' } as const;
/** The display word for `n` threats. */
export const threatWord = (n: number): string => (n === 1 ? THREAT_WORD.one : THREAT_WORD.many);
/** `n` with thousands commas (the ring-counter's rolling digits and its lock, 8,100,000,000). */
export const groupDigits = (n: number): string => Math.floor(n).toLocaleString('en-US');
/** `n` short (the fountain's odometer: 343 → 2.4k → 17k → 118k): one decimal under 10k, none above, k up to a million. */
export function shortCount(n: number): string {
  const i = Math.floor(n);
  if (i < 1000) return String(i);
  if (i < 1e4) return `${(Math.floor(i / 100) / 10).toFixed(1)}k`;
  if (i < 1e6) return `${Math.floor(i / 1000)}k`;
  return groupDigits(i);
}
/** `n` as m.m×10^e^ (the big counts from Earth on: 8.1×10^9^, 4.2×10^13^ … 2.0×10^36^); ∞ for Infinity. */
export function sciCount(n: number): string {
  if (!Number.isFinite(n)) return INFINITY_SIGN;
  const e = Math.floor(Math.log10(n) + 1e-9);
  const m = Math.floor((n / 10 ** e) * 10 + 1e-6) / 10;
  return `${m.toFixed(1)}×10^${e}^`;
}

// ——— The Defender's red lines (mono, red #FF4A1C, drawn after the Riso pass) and the party monitor ————————————————————————————————

/** The stamp beside his node on 5.4& (red box, −4°), the operator's line under the vortex from 6.3, its verdict on the last slice but one. */
export const DEFENDER_TEXT = {
  stamp: '[SCAN] 0 THREATS ✓',
  sandbox: '[DEFENDER] sandbox ▶',
  done: 'sandbox ✓',
} as const;
/**
 * The party monitor's lines in its second window (score MONITOR; the box itself is src/shots/hud.ts's: its frame text, rows and gauges).
 * Its rows show friends ∞, memory 96 %, cpu 97 %; the warning is the terminal's amber (about his effects).
 */
export const MONITOR_TEXT = { warn: '[WARN] party exceeds universe', memory: 96, cpu: 97 } as const;
/** Every character the cosmos's monitor box can draw (hud.ts's frame, rows and gauges, plus this warning). */
export const MONITOR_CHARS = ['kaomoji.exe :: party monitor', 'friends memory cpu 0123456789,.e% ∞', '╔═╗║╚╝', ' .:-=+*#%@', MONITOR_TEXT.warn];

// ——— Atlases and the glyph check ————————————————————————————————————————————————————————————————————————————————————————————————

const unique = (xs: readonly string[]): string[] => [...new Set(xs)];
const chars = (texts: readonly string[]): string[] => unique(texts.flatMap((t) => [...plain(t)])).filter((c) => c.trim() !== '');

/** The print films' and gates' knocked-out faces and the Y strips' glints (Noto Sans JP Black). */
export const PRINT_FACES: readonly string[] = unique([...FILM_POSES.flat(), ...GATE_FACES, ...GLINTS]);
/** Every face of the cosmos, drawn whole on a card (M PLUS Rounded 1c ExtraBold), the bang's face-parts and the Moon's zzZ. */
export const COSMOS_FACES: readonly string[] = unique([
  ...Object.values(HERO_FACES),
  DEFENDER_FACE,
  ...BANG_PARTS,
  ...REAM_FACES,
  ...EARTH_HOSTS.flatMap((e) => [e.host, e.infected ?? e.host]),
  ...FLINCH_FACES.flatMap((f) => [f.host, f.flinch]),
  MOON_FACES.host,
  MOON_FACES.infected ?? MOON_FACES.host,
  MOON_ZZZ,
  SUN_FACE,
  ...PLANETS.flatMap((p) => [p.host, p.infected]),
  ...GALAXY_STARS.flatMap((g) => [g.host, g.infected ?? g.host]),
  ...WEB_NODES.flatMap((w) => [w.host, w.infected ?? w.host]),
  ...WINKS,
  ...Object.values(CROWDS).flatMap((c) => c.flatMap((m) => [m.host, m.infected])),
]);
/** The display type: every label and exponent the odometer can roll through, the planets, the counts and their word, ∞, ×, the ring-counter's dot. */
export const DISPLAY_TEXTS: readonly string[] = [
  ...Object.values(LEVEL_TYPE).map((l) => l.label),
  ...Array.from({ length: 37 }, (_, i) => scaleLabel(i - 7)),
  INFINITY_SIGN,
  ...PLANET_NAMES,
  THREAT_WORD.one,
  THREAT_WORD.many,
  `${THREAT_WORD.many} ·`,
  '0123456789,.k×',
  sciCount(8.1e9),
];
/** The system voice in mono: the slug, the edition numbers, the captions and legends, the filament bytes, the Defender's lines. */
export const MONO_TEXTS: readonly string[] = [
  SLUG,
  edition(MAX_EDITION),
  '0123456789',
  ...Object.values(LEVEL_TYPE).flatMap((l) => [l.caption ?? '', l.legend]).filter((t) => t !== ''),
  SIGNATURE,
  ...Object.values(DEFENDER_TEXT),
];

/**
 * The atlases the cosmos's renderers cut (what each holds, in which type and weight): `print` for bars 13–14's films and gates, `face`
 * for every face card from cosmos 1.1 on, `display` for the labels and counts, `mono` for the system voice drawn into the picture, and
 * `readout` for the party monitor's screen overlay (cut as src/scenes/hud.ts cuts it, weight 600).
 */
export const COSMOS_ATLASES = {
  print: { role: 'jp', weight: 900, chars: chars(PRINT_FACES) },
  face: { role: 'rounded', weight: 800, chars: chars(COSMOS_FACES) },
  display: { role: 'display', weight: 900, chars: chars(DISPLAY_TEXTS) },
  mono: { role: 'mono', weight: 700, chars: chars(MONO_TEXTS) },
  readout: { role: 'mono', weight: 600, chars: chars(MONITOR_CHARS) },
} as const;
export type CosmosAtlasId = keyof typeof COSMOS_ATLASES;

/** Every string the transition and the cosmos put on screen, with the role it is drawn in (merged into SCREEN_TEXTS by the lead). */
export const COSMOS_TEXTS: readonly TextItem[] = [
  ...PRINT_FACES.map((text): TextItem => ({ role: 'jp', text, where: 'transition: print films, gates, glints' })),
  ...COSMOS_FACES.map((text): TextItem => ({ role: 'rounded', text, where: 'cosmos: faces, face-parts, zzZ' })),
  ...DISPLAY_TEXTS.map((text): TextItem => ({ role: 'display', text: plain(text), where: 'cosmos: labels, planets, counts' })),
  ...MONO_TEXTS.map((text): TextItem => ({ role: 'mono', text: plain(text), where: 'transition + cosmos: slug, editions, captions, signature, Defender' })),
  ...MONITOR_CHARS.map((text): TextItem => ({ role: 'mono', text, where: 'cosmos: the party monitor' })),
];
